<div class="container container-fluid">
<h1>Eventos pagos</h1>
<div class="noBackground">
<table border="1" class="table table-hover eventos-pagos">
	<tr>
		<th>Título do evento</th>
		<th>Inscrições até</th>
		<th>Data da inscrição</th>
		<th>Situação do pagamento</th>
	</tr>
	<?php foreach ($pagos as $evento): ?>
	<tr>
		<td><?= $evento['titulo'] ?></td>
		<td><?= $evento['data_limite'] ?></td>
		<td><?= $evento['data_inscricao'] ?></td>
		<td><?= $evento['pagamento'] == 1 ? 'Pago' : '<a href="'.$evento['url'].'" target="_blank">Pagar com pagseguro</a>' ?></td>
	</tr>
	<?php endforeach; ?>
</table>
</div>
<h1>Eventos com pagamento pendente</h1>
<div class="noBackground">
<table border="1" class="table table-hover eventos-pagos">
	<tr>
		<th>Título do evento</th>
		<th>Inscrições até</th>
		<th>Data da inscrição</th>
		<th>Situação do pagamento</th>
	</tr>
	<?php foreach ($pendentes as $evento): ?>
	<tr>
		<td><?= $evento['titulo'] ?></td>
		<td align="center"><?= $evento['data_limite'] ?></td>
		<td align="center"><?= $evento['data_inscricao'] ?></td>
		<td align="center"><?= $evento['pagamento'] == 1 ? 'Pago' : '<a class="btn btn-primary" href="'.$evento['url'].'" target="_blank">Pagar com pagseguro</a>' ?></td>
	</tr>
	<?php endforeach; ?>
</table>
</div>
</div>