<script type="text/javascript">
  $(document).ready(function() {
    $(".accordion .accord-header").click(function() {
      if($(this).next("div").is(":visible")){
        $(this).next("div").slideUp("slow");
      } else {
        $(".accordion .accord-content").slideUp("slow");
        $(this).next("div").slideToggle("slow");
      }
    });
  });
function esconder(div){
    if($('#'+div).is(":visible") )
      $('#'+div).fadeOut(800);
    else
      $('#'+div).fadeIn(800);
  }
</script>
</body>
</html>