<?php
$info      = Evento::getEvento($id_evento, 'all');

$titulo    = $info[0]['titulo'];
$vagas     = $info[0]['vagas'];
$descricao = $info[0]['desc_evento'];
$local     = $info[0]['local'];
$final     = $info[0]['data_limite']; 
$valor = isset($info[0]['valor']) ? $info[0]['valor'] : null;
/*$today = date("Y-m-d");*/
if($final == null){
	App::redirect('user');
}
if(!($vagas > 0)){
	$valor = null;
}
?>
<style type="text/css">
	.row{background: white!important}
	.caution{clear: both;color: red!important; text-shadow: 1px 1px 1px black;}
</style>
<div class="page-content">
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title"><small>Você está prestes a se cadastrar no evento -</small><br><?= $titulo?></h1>
				<b>Descrição:</b>
				<div class='Descricao' style="border:solid 1px gray">
					<p><?= $descricao; ?></p>
				</div>
				<b>Valor do evento:</b>
				<div>
					<p><?= $valor ? 'R$'.$valor : 'Inscrições não estão abertas' ?></p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget">
					
					<?php if(!($vagas > 0)): ?>
					<div>
						<h2 class="caution">Desculpe, você não pode se cadastrar nesse evento, inscrições encerradas!</h2>
					</div>
					<?php else: ?>
					<div class="widget-header"> <i class="icon-align-left"></i>
						<h3>Inscrições para esse evento até <b>&nbsp;<?=$final;?></b></h3>
						<h3>Restam <b><?=$vagas;?></b> vagas.</h3>
					</div>
					<?php endif; ?>
					
					<div class="widget-content">
						<?php if (Subevento::exists($id_evento)): ?>
							<?php $data = Subevento::getSubevento($id_evento, null, 'all');	?>
							<fieldset>
								<legend class="section">Seleione os subeventos que deseja se inscrever</legend>
								<div class="control-group">
									<table class="subeventos table table-striped table-bordered">
										<thead>
											<tr>
												<th> Selecione </th>
												<th> Titulo </th>
												<th> Descricao </th>
												<th> Data Limite das inscricoes </th>
												<th> Vagas Restantes </th>
												<th> Valor Atual </th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($data as $d): ?>
											<?php $valor_subevento = Subevento::getValueSubeventoById($d['id_subevento']); ?>
											<?php if($valor_subevento && ($d['vagas'] > 0)): ?>
												<tr>
													<td style="text-align:center"> <input type="checkbox" name="subevento" value="<?= $d['id_subevento'] ?>" id="checkbox<?= $d['id_subevento'] ?>" class="css-checkbox">
														<label for="checkbox<?= $d['id_subevento'] ?>" class="css-label"></label>
													 </td>
													<td> <?=$d['titulo'];?> </td>
													<td> <?= $d['descricao'] ?> </td>
													<td> <?= $d['data_limite']; ?></td>
													<td> <?= $d['vagas'];?> </td>
													<td class="valor-subevento"> R$<span class="price-subevento"><?= $valor_subevento;?> </span></td>
												</tr>
											<?php else: ?>
												<tr>
													<td style="text-align:center"> <input type="checkbox" disabled name="subevento" value="<?= $d['id_subevento'] ?>" id="checkbox<?= $d['id_subevento'] ?>" class="css-checkbox">
														<label for="checkbox<?= $d['id_subevento'] ?>" class="css-label"></label>
													 </td>
													<td> <?=$d['titulo'];?> </td>
													<td> <a href="#">Ver Descrição</a> </td>
													<td> <?= $d['data_limite']; ?></td>
													<td> <?= $d['vagas'] ? $d['vagas'] : 'Vagas esgotadas';?> </td>
													<td class="valor-subevento"> R$<span class="price-subevento"><?= $valor_subevento;?> </span></td>
												</tr>
											<?php endif; ?>
										<?php endforeach;?>
										<tr>
											<td colspan="6" align="center"></td>
										</tr>
										</tbody>
									</table>
								</div>
							</fieldset>
						<?php endif;?>
							<fieldset>
								<legend class="section">Finalizar Inscrição - </legend>
								<form id="payment" action="<?= App::getUrl('inscricao/payment/') ?>" method="POST">
									<div class="control-group">
										<div class="valor-total form-group">
										
											<h1>Valor total: R$ <span class="preco-total"><?= $valor ?></span></h1>
										</div>
										<input type="hidden" name="total" class="preco-total" value="<?= $valor ?>">
										<input type="hidden" name="id_evento" value="<?= $id_evento ?>">
										<div class="controls form-group" style="text-align:center">
											<input type="submit" class="btn-lg btn-primary" <?= $valor ? '' : 'disabled' ?> value="Pagamento Seguro">
										</div>
									</div>
									<div class="control-group" id="cidade" style="display:none">
										<label for="hint-field" class="control-label"> Cidade </label>
										<div class="controls form-group">
											<div class="cidade"></div>
										</div>
									</div>
								</form>
							</fieldset>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$('input:[name=subevento]').change(function(){
		var id_subevento = $(this).val();
		var price_subevento = Number($(this).parent().parent().children('.valor-subevento').children('.price-subevento').html());
		if($(this).prop('checked')){
			var i = $('#payment input.subeventos').length;
			$('#payment').append('<input type="hidden" class="subeventos" name="subevento['+i+']" value="'+id_subevento+'">');
			
			price_subevento += Number($('#payment input.preco-total').val());

			$('#payment span.preco-total').html(price_subevento);
			$('#payment input.preco-total').val(price_subevento);
		}else{
			price_subevento = Number($('#payment input.preco-total').val()) - price_subevento;
			$('#payment span.preco-total').html(price_subevento);
			$('#payment input.preco-total').val(price_subevento);
			$('#payment .subeventos[value='+id_subevento+']').remove();
		}
	});
</script>