
<div class="page-content">
  <div class="content container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="page-title">Eventos <small>Veja aqui a lista dos eventos disponiveis para inscrção</small></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget">
          <div class="widget-content">
          <?php if(Evento::exists()): ?>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Título do Evento</th>
                  <th>Inscrições até</th>
                  <th>Inscrever-se</th>
                  <th>Ver Subeventos</th>
                </tr>
              </thead>
              <tbody>
              <?php $eventos = Evento::getEvento(null, 'all');?>
              <?php foreach ($eventos as $evento):?>
                <tr>
                  <td><?= $evento['titulo']?></td>
                  <td><?= $evento['data_limite']?></td>
                  <td><a href="<?= App::getUrl()?>inscricao/execute/<?= $evento['id_evento']?>" class="btn btn-primary">Inscrever-se</span></td>
                  <td><span class="btn btn-success" onclick="esconder('_<?=$evento['id_evento']?>');">Subeventos</span></td>
                </tr>
                <?php if(Subevento::exists($evento['id_evento'])): ?>
                <tr>
                <td colspan="4" id="_<?=$evento['id_evento']?>" style="padding:10px 100px 0px; display:none"><table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Nome do Subevento</th>
                      <th>Descricao</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php $subeventos = Subevento::getSubevento($evento['id_evento'],null, 'all');?>
                    <?php foreach ($subeventos as $subevento):?>
                    <tr>
                      <td><?= $subevento['titulo'] ?></td>
                      <td><?= $subevento['descricao'] ?></td>
                    </tr>
                  <?php endforeach;?>
                  </tbody>
                </table>
                </td></tr>
              <?php else:?>
                <tr style="display:none;" id='_<?=$evento['id_evento']?>'><td colspan="4" style="text-align:center"><h3>Este é um Evento Simples - Não existem Subeventos</h3></td></tr>
              <?php endif;?>
              <?php endforeach;?>
              </tbody>
            </table>
          <?php else:?>
              <h2>Não há Eventos Cadastrados</h2>
          <?php endif;?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
