<?php $id_evento = (string)$params[0];?>

<?php if(Subevento::exists($id_evento)):?>
	<div class="h_right">
			<div class="wrap">
				<h3>Últimos eventos</h3>
				<p>Veja as fotos dos últimos eventos realizados na UTFPR.</p>
			</div>
	</div>
	<div class="row" style="margin:0 auto">
	<?php $sub = Subevento::getSubevento($id_evento, null , 'all') ?>
	<?php foreach ($sub as $s): ?>
				<div class="col_1_of_3 span_1_of_3">
					<div class="title-event"><h4><a href="#"><?= $s['titulo']; ?></a></h4></div>
					<?php Page::addImage('baner-250X200.png', '') ?>
					<p>Veja os Detalhes na <a href="<?= App::getUrl()?>evento/view/3/<?=$s['id_subevento']?>">Pagina do Evento</a></p>
					<!-- <a href="//www.youtube.com/embed/D3W1nXeFe_Q" target="_black">veja o video</a> --> 
				</div>
			<?php endforeach;?>
			</div>
		
<?php endif;?>


<div class="h_right">
			<div class="wrap">
		<h3>Fotos Do Evento </h3>
		<p style="text-align:center">Veja as fotos dos últimos eventos realizados na UTFPR.</p>
</div>
</div>
		<div class="page-content">
			<div class="content container">
				<div class="row">
					<div class="col-lg-12">
						<div class="widget">
							<div class="widget-content">
								<div id="examples" class="section examples-section">
									<?php if( Media::image_exists($id_evento) ){
										echo Media::getAllImages($id_evento); 
									}else{ ?>
									<h3><p> Ainda não há Imagens para este Evento </p></h3>
									<?php } ?>
									<div class="clear"></div>	
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="clear"></div>
		</div>
	</div>

<div class="h_right">
			<div class="wrap">
			<h3>Videos</h3>
			<p>Veja os videos do evento?</p>
			</div>
			</div>
			<?php if( Media::Video_exists($id_evento) ){
				echo Media::getAllVideos($id_evento); 
			}else{ ?>
			<h3><p> Ainda não há Videos para este Evento </p></h3>
			<?php } ?>
			<div class="clear"></div>								  						
		</div>   		 
	</div>
	<div class="about" id="about">
		<div class="wrap">
			<h3>SOBRE O EVENTOS</h3>
			<p class="a">sobre o que é este evento?</p>
			<div class="about-time-line">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
			</div>
		</div>    
	</div>

	<div class="t-clients">
		<div class="wrap"> 				
			<div class="nbs-flexisel-container">
				<div class="nbs-flexisel-inner">
					<ul class="flexiselDemo3 nbs-flexisel-ul" style="left: -253.6px; display: block;">			<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
						<?php Page::addImage('facebook.png', '') ?>
					</li>
					<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
						<?php Page::addImage('java.jpeg', '') ?>
					</li>
					<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
						<?php Page::addImage('microsoft.gif', '') ?>
					</li>
					<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
						<?php Page::addImage('php.png', '') ?>
					</li>
					<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
						<?php Page::addImage('yahoo.png', '') ?>
					</li>
				</ul>
				<div class="nbs-flexisel-nav-left" style="top: 21.5px;"></div>
				<div class="nbs-flexisel-nav-right" style="top: 21.5px;"></div>
			</div>
		</div> 
		<div class="clear"> </div> 
		<?php
		Page::addStyleElement('js', 'jquery.flexisel.js');
		?>     
		<script type="text/javascript">
			$(window).load(function() {$(".flexiselDemo3").flexisel({visibleItems: 5,        animationSpeed: 1000, autoPlay: true,autoPlaySpeed: 3000,pauseOnHover: true,
				enableResponsiveBreakpoints: true,responsiveBreakpoints: {portrait: { 
					changePoint:480,visibleItems: 1},landscape: { changePoint:640,visibleItems: 2
					},tablet: {changePoint:768,visibleItems: 3}}});});
		</script>
	</div>				
</div>