<?php $id_evento = (string)$params[0];?>

<div class="services" id="ultimos">
		<div class="wrap">
			<h3>Fotos Do Evento </h3>
			<p style="text-align:center">Veja as fotos dos últimos eventos realizados na UTFPR.</p>
			
			<div class="page-content">
    <div class="content container">
      <div class="row">
        <div class="col-lg-12">
          <div class="widget">
            <div class="widget-content">
              <div id="examples" class="section examples-section">
                 <?php if( Media::image_exists($id_evento) ): ?>
                 	<?php 
                 		$images = Media::getAllImages($id_evento);
                 		foreach ($images as $image):
                 	?>
		                <div class="col-sm-4 col-md-2">
		                  <div class="image-row">
		                    <div class="image-set"> <a href="<?= Page::urlImage('baner-250X200.png'); ?>" data-lightbox="example-set" title="Clique ao lado da imagen para ir para as proximas fotos"><?php Media::addImage('baner-250X200.png', '') ?></a> </div>
		                  </div>
		                </div>
		               <?php endforeach; ?>
	             <?php else: ?>
	             	<h1> Ainda não há Imagens para este Evento </h1>
	             <?php endif; ?>
                
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

		<div class="clear"></div>
	</div>
</div>

<div class="portfolio" id="proximos">
	<div class="wrap">
		<h3>Videos</h3>
		<p>Veja os videos do evento?</p>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>
		<div class="col_1_of_3 span_1_of_3">
			<video autobuffer autoloop loop controls>
				<source src="/media/video.oga">
				<source src="/media/video.m4v">
				<object type="video/ogg" data="/media/video.oga" width="320" height="240">
				<param name="src" value="/media/video.oga">
				<param name="autoplay" value="false">
				<param name="autoStart" value="0">
				<p><a href="/media/video.oga">Download this video file.</a></p>
				</object>
			</video>
			<h4><a href="#">Semana acadêmica 2014</a></h4>
		</div>	
		<div class="clear"></div>								  						
	</div>   		 
</div>
<div class="about" id="about">
	<div class="wrap">
		<h3>SOBRE O EVENTOS</h3>
		<p class="a">sobre o que é este evento?</p>
		<div class="about-time-line">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
		</div>
	</div>    
</div>

<div class="t-clients">
	<div class="wrap"> 				
		<div class="nbs-flexisel-container">
			<div class="nbs-flexisel-inner">
				<ul class="flexiselDemo3 nbs-flexisel-ul" style="left: -253.6px; display: block;">			<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
					<?php Page::addImage('facebook.png', '') ?>
				</li>
				<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
					<?php Page::addImage('java.jpeg', '') ?>
				</li>
				<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
					<?php Page::addImage('microsoft.gif', '') ?>
				</li>
				<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
					<?php Page::addImage('php.png', '') ?>
				</li>
				<li onclick="location.href='#';" class="nbs-flexisel-item" style="width: 253.6px;">
					<?php Page::addImage('yahoo.png', '') ?>
				</li>
			</ul>
			<div class="nbs-flexisel-nav-left" style="top: 21.5px;"></div>
			<div class="nbs-flexisel-nav-right" style="top: 21.5px;"></div>
		</div>
	</div> 
	<div class="clear"> </div> 
	<?php
	Page::addStyleElement('js', 'jquery.flexisel.js');
	?>     
	<script type="text/javascript">
		$(window).load(function() {$(".flexiselDemo3").flexisel({visibleItems: 5,        animationSpeed: 1000, autoPlay: true,autoPlaySpeed: 3000,pauseOnHover: true,
			enableResponsiveBreakpoints: true,responsiveBreakpoints: {portrait: { 
				changePoint:480,visibleItems: 1},landscape: { changePoint:640,visibleItems: 2
				},tablet: {changePoint:768,visibleItems: 3}}});});
	</script>
</div>				
</div>