<?php
include_once 'core/App.class.php';
 App::ready();
?>
<!DOCTYPE HTML>
<html>
<head>
	<title>Eventos - UTFPR - Campus Guarapuava</title>

	<?php
	Page::addStyleElement('css', 'bootstrap.min.css');
	Page::addStyleElement('css', 'slider.css');
	Page::addStyleElement('css', 'style.css');
	Page::addStyleElement('css', 'custom.css');
	Page::addStyleElement('js', 'custom.js');
	?>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700,600,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<?php
		Page::addStyleElement('js', 'jquery.min.js');
		Page::addStyleElement('js', 'modernizr.custom.28468.js');
		Page::addStyleElement('js', 'jquery.cslider.js');
		Page::addStyleElement('js', 'efeitos.js');
		Page::addStyleElement('js', 'default.js');
		 Page::addThinElement('css', 'screen.css');
		 Page::addThinElement('css', 'lightbox.css');

		Page::addStyleElement('js','lib/jquery-1.10.1.min.js');
		Page::addStyleElement('js','lib/jquery.mousewheel-3.0.6.pack.js');
		Page::addStyleElement('js','../css/source/jquery.fancybox.js');
		Page::addStyleElement('css','source/jquery.fancybox.css');
		Page::addStyleElement('css','source/helpers/jquery.fancybox-buttons.css');
		Page::addStyleElement('js','../css/source/helpers/jquery.fancybox-buttons.js');
		Page::addStyleElement('css','source/helpers/jquery.fancybox-thumbs.css');
		Page::addStyleElement('js','../css/source/helpers/jquery.fancybox-thumbs.js');
		Page::addStyleElement('js','../css/source/helpers/jquery.fancybox-media.js');
	?>


	<script type="text/javascript">
		$(document).ready(function() {

			$('.fancybox').fancybox();
			$(".fancybox-effects-d").fancybox({
				padding: 0,
				openEffect : 'elastic',
				openSpeed  : 150,
				closeEffect : 'elastic',
				closeSpeed  : 150,
				closeClick : true,
				helpers : {
					overlay : null
				}
			});
		});
	</script>
	<style type="text/css">
		.fancybox-custom .fancybox-skin {
			box-shadow: 0 0 50px #222;
		}
	</style>
<style>
	.slider_bg_evento{background: url("<?= App::getUrl()?>assets/images/fundo2.jpg") no-repeat;background-size: 100%}
</style>
	<?php if($_COOKIE['boas_vindas'] == '0' ): ?>
		<script type="text/javascript">
			$(document).ready(function () {
				$('.boas-vindas').show();
				$('#fancybox').show();
			});
			<?php App::cookie('1'); ?>
		</script>
	<?php endif ?>

</head>
<body>
	<div class="slider_bg_evento">
		<div class="h_right">
			<div class="menu" id="bt_menu">
				<div class="bt_menu">
					<p class="listar-menu"></p>
					<p class="listar-menu"></p>
					<p class="listar-menu"></p>
					<span>Menu</span>
				</div>
			</div>
			<span><!--<?php echo 'pagina' ?>-->Listar Eventos</span>
			<nav class="nav">
				<ul class="nav-list">
					<li class="nav-item"></span><a href="<?= App::getUrl() ?>">Home</a></li>
					<li class="nav-item"><a href="<?= App::getUrl() ?>login/verify/user">Área do Participante</a></li>
					<li class="nav-item"><a href="<?= App::getUrl() ?>login/verify/adm">Área do Administrador</a></li>
				</ul>
			</nav>
			<?php
			Page::addStyleElement('js', 'responsive.menu.js');
			?>
		</div>
		<div id="menu_oculto">
			<ul>		
				<li><a href="<?= App::getUrl() ?>"><span class="glyphicon glyphicon-collapse-down"></span>&nbsp;Home</a></li>
				<li><a href="<?= App::getUrl() ?>login/verify/user"><span class="glyphicon glyphicon-user"></span>	&nbsp;Área do Participante</a></li>
				<li><a href="<?= App::getUrl() ?>login/verify/admin"><span class="glyphicon glyphicon-user"></span>	&nbsp;Área do Administrador</a></li>
			</ul>
		</div>
		<div class="wrap">
			<div class="header">
				<div class="fundo-logo">
					<div class="logo">
						<a href="index.html"><?php Page::addImage('logo.png', '');?></a>
					</div>
				</div>
				<div class="clear"></div>

			</div>
		</div>
		<div class="title" style="margin-top:10px!important;padding-bottom:150px"><h2>Eventos UTFPR</h2></div>
	</div>