<?php
include_once 'core/App.class.php';
?>
<!DOCTYPE HTML>
<html>
<head>
	<title>Eventos - UTFPR - Campus Guarapuava</title>

	<?php
	Page::addStyleElement('css', 'bootstrap.min.css');
	Page::addStyleElement('css', 'slider.css');
	Page::addStyleElement('css', 'style.css');
	Page::addStyleElement('css', 'custom.css');
	?>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700,600,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<?php
	Page::addStyleElement('js', 'jquery.min.js');
	Page::addStyleElement('css', 'css/slider.css');
	Page::addStyleElement('js', 'modernizr.custom.28468.js');
	Page::addStyleElement('js', 'jquery.cslider.js');
	Page::addStyleElement('js', 'efeitos.js');
	Page::addStyleElement('js', 'fancybox/jquery.fancybox-1.3.4.js');
	Page::addStyleElement('js', 'fancybox/jquery.fancybox-1.3.4.pack.js');
	Page::addStyleElement('js', 'fancybox/jquery.mousewheel-3.0.4.pack.js');
	Page::addStyleElement('css', 'jquery.fancybox-1.3.4.css');
	Page::addStyleElement('js', 'default.js');

	 Page::addThinElement('css', 'screen.css');
	 Page::addThinElement('css', 'lightbox.css');

	?>


	<?php if(!isset($_COOKIE['boas_vindas'])): ?>
		<script type="text/javascript">
			$(document).ready(function () {
				$('.boas-vindas').show();
				$('#fancybox').show();
			});
		</script>
		<?php setcookie("boas_vindas", 'cadastrado', time()+3600*24*30*12*50); ?>
	<?php endif ?>

</head>
<body>
	<div class="slider_bg_evento">
		<?php Page::addImage('palestra3.jpg', 'alt="fundo" width="100%" height="785px" style="position:absolute;z-index:-1;max-width:100%;"');?>
		<div class="h_right">
			<div class="menu" id="bt_menu">
				<div class="bt_menu">
					<p class="listar-menu"></p>
					<p class="listar-menu"></p>
					<p class="listar-menu"></p>
					<span>Menu</span>
				</div>
			</div>
			<span><!--<?php echo 'pagina' ?>-->Listar Eventos</span>
			<nav class="nav">
				<ul class="nav-list">
					<li class="nav-item"></span><a href="<?= App::getUrl() ?>">Home</a></li>
					<li class="nav-item"><a href="<?= App::getUrl() ?>login/verify/user">Área do Participante</a></li>
					<li class="nav-item"><a href="<?= App::getUrl() ?>login/verify/adm">Área do Administrador</a></li>
				</ul>
			</nav>
			<?php
			Page::addStyleElement('js', 'responsive.menu.js');
			?>
		</div>
		<div id="menu_oculto">
			<ul>		
				<li><a href="<?= App::getUrl() ?>"><span class="glyphicon glyphicon-collapse-down"></span>&nbsp;Home</a></li>
				<li><a href="<?= App::getUrl() ?>login/verify/user"><span class="glyphicon glyphicon-user"></span>	&nbsp;Área do Participante</a></li>
				<li><a href="<?= App::getUrl() ?>login/verify/admin"><span class="glyphicon glyphicon-user"></span>	&nbsp;Área do Administrador</a></li>
			</ul>
		</div>
		<div class="wrap">
			<div class="header">
				<div class="fundo-logo">
					<div class="logo">
						<a href="index.html"><?php Page::addImage('logo.png', '');?></a>
					</div>
				</div>
				<div class="clear"></div>

			</div>
		</div>
		<div id="da-slider" class="da-slider">
			<div class="da-slide">
				<p>O melhor sistema de eventos!</p>
				<h2>Eventos UTFPR</h2>
				<p class="a"><a href="#">Quer ter este sistema no seu site?</a></p>
			</div>
			<div class="da-slide">
				<p>Veja fotos dos</p>
				<h2>Últimos eventos</h2>
				<p class="a"><a href="#">Veja mais!</a></p>
			</div>
			<div class="da-slide">
				<p>Fique por dentro dos</p>
				<h2>Próximos eventos</h2>
				<p class="a"><a href="#">Veja mais</a></p>
			</div>
			<div class="da-slide">
				<p>Gostou do sistema?</p>
				<h2>CONTRATE-NOS</h2>
				<p class="a"><a href="#">Saber mais</a></p>
			</div>	

			<nav class="da-arrows">
				<span class="da-arrows-prev"></span>
				<span class="da-arrows-next"></span>
			</nav>
		</div>
	</div>