<div class="services" id="ultimos">
	<div class="wrap">
		<h3>Listagem dos Eventos</h3>
		<p>Veja os eventos da UTFPR.</p>
			<div class="row">
        <div class="col-lg-12">
          <div class="widget">
            <div class="widget-content">
              <div class="body">
                <table class="table table-striped table-images">
                  <thead>
                    <tr>
                      <th class="hidden-xs-portrait">#</th>
                      <th>Miniatura</th>
                      <th>Descrição</th>
                      <th class="hidden-xs-portrait">Informação</th>
                      <th class="hidden-xs">Data do Evento</th>
                      <th class="hidden-xs">Inscriçoes Até</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td class="hidden-xs-portrait">1</td>
                      <td><img src="images/1.jpg"></td>
                      <td> Palestra de Desenvolvimento Ágil </td>
                      <td class="hidden-xs-portrait"><p> <small> <strong>Tipo:</strong> &nbsp; Desenvolvimento Ágil com Scrum </small> </p>
                      <td class="hidden-xs"> 14/072014 </td>
                      <td class="hidden-xs"> 10/07/2014 </td>
                      <td><button class="btn btn-sm btn-primary"> Visualizar </button>
                        <button data-toggle="button" class="btn btn-sm btn-warning"> Inscrever-se </button></td>
                    </tr>
                    <tr>
                      <td class="hidden-xs-portrait">2</td>
                      <td><img src="images/1.jpg"></td>
                      <td> Palestra de Desenvolvimento Ágil </td>
                      <td class="hidden-xs-portrait"><p> <small> <strong>Tipo:</strong> &nbsp; Desenvolvimento Ágil com Scrum </small> </p>
                      <td class="hidden-xs"> 14/072014 </td>
                      <td class="hidden-xs"> 10/07/2014 </td>
                      <td><button class="btn btn-sm btn-primary"> Visualizar </button>
                        <button data-toggle="button" class="btn btn-sm btn-warning"> Inscrever-se </button></td>
                    </tr>
                    <tr>
                      <td class="hidden-xs-portrait">3</td>
                      <td><img src="images/1.jpg"></td>
                      <td> Palestra de Desenvolvimento Ágil </td>
                      <td class="hidden-xs-portrait"><p> <small> <strong>Tipo:</strong> &nbsp; Desenvolvimento Ágil com Scrum </small> </p>
                      <td class="hidden-xs"> 14/072014 </td>
                      <td class="hidden-xs"> 10/07/2014 </td>
                      <td><button class="btn btn-sm btn-primary"> Visualizar </button>
                        <button data-toggle="button" class="btn btn-sm btn-warning"> Inscrever-se </button></td>
                    </tr>
                    <tr>
                      <td class="hidden-xs-portrait">4</td>
                      <td><img src="images/1.jpg"></td>
                      <td> Palestra de Desenvolvimento Ágil </td>
                      <td class="hidden-xs-portrait"><p> <small> <strong>Tipo:</strong> &nbsp; Desenvolvimento Ágil com Scrum </small> </p>
                      <td class="hidden-xs"> 14/072014 </td>
                      <td class="hidden-xs"> 10/07/2014 </td>
                      <td><button class="btn btn-sm btn-primary"> Visualizar </button>
                        <button data-toggle="button" class="btn btn-sm btn-warning"> Inscrever-se </button></td>
                    </tr>
                    <tr>
                      <td class="hidden-xs-portrait">5</td>
                      <td><img src="images/1.jpg"></td>
                      <td> Palestra de Desenvolvimento Ágil </td>
                      <td class="hidden-xs-portrait"><p> <small> <strong>Tipo:</strong> &nbsp; Desenvolvimento Ágil com Scrum </small> </p>
                      <td class="hidden-xs"> 14/072014 </td>
                      <td class="hidden-xs"> 10/07/2014 </td>
                      <td><button class="btn btn-sm btn-primary"> Visualizar </button>
                        <button data-toggle="button" class="btn btn-sm btn-warning"> Inscrever-se </button></td>
                    </tr>
                  </tbody>
                </table>
                <div class="clearfix">
                  <div class="pull-right">
                  </div>
                  <ul class="pagination no-margin">
                    <li class="disabled"><a href="#">Prev</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
	<?php
	Page::addStyleElement('js', 'jquery.flexisel.js');
	?>     
	<script type="text/javascript">
		$(window).load(function() {$(".flexiselDemo3").flexisel({visibleItems: 5,        animationSpeed: 1000, autoPlay: true,autoPlaySpeed: 3000,pauseOnHover: true,
			enableResponsiveBreakpoints: true,responsiveBreakpoints: {portrait: { 
				changePoint:480,visibleItems: 1},landscape: { changePoint:640,visibleItems: 2
				},tablet: {changePoint:768,visibleItems: 3}}});});
	</script>
</div>				
</div>
