<div class="services" id="ultimos">
	<div class="wrap">
		<h3>Listagem dos Eventos</h3>
		<p>Veja os eventos da UTFPR.</p>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget">
					<div class="widget-content">
						<div class="body">
							<?php if(Evento::exists()): ?>
								<table class="table table-striped table-images">
									<thead>
										<tr>
											<th class="hidden-xs-portrait">#</th>
											<!-- <th>Miniatura</th> -->
											<th>Nome do Evento</th>
											<th class="hidden-xs-portrait">Informação</th>
											<th class="hidden-xs">Data do Evento</th>
											<th class="hidden-xs">Inscriçoes Até</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
										<?php $n=0;
											  $data = Evento::getEvento(null,'info'); 
									    ?>
										<?php foreach ($data as $key): ?>
											<?php $n++; ?>
											<tr>
												<td class="hidden-xs-portrait"><?= $n; ?></td> 
												<!-- <td><img src="images/1.jpg"></td> -->
												<td class="hidden-xs-portrait"><p> <small> <?= $key['titulo']; ?> </small> </p></td>										
												<td> <?= $key['descricao_resumida']; ?> </td>
												<td class="hidden-xs"> <?= $key['data_hora']; ?></td>
												<td class="hidden-xs"> <?= $key['data_limite']; ?> </td>
												<td>
													<a class="btn btn-sm btn-primary" href="view/<?=$key['id_evento']?>" style="margin-bottom:5px"> Visualizar </a>
													<a class="btn btn-sm btn-warning" href="<?=App::getUrl()?>inscricao/execute/<?=$key['id_evento']?>" style="margin-bottom:5px"> Inscrever-se </a>
												</td>
											</tr>
										<?php endforeach; ?>
							<?php endif; ?>		

										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php	Page::addStyleElement('js', 'jquery.flexisel.js');	?>     
			<script type="text/javascript">
				$(window).load(function() {$(".flexiselDemo3").flexisel({visibleItems: 5,        animationSpeed: 1000, autoPlay: true,autoPlaySpeed: 3000,pauseOnHover: true,
					enableResponsiveBreakpoints: true,responsiveBreakpoints: {portrait: { 
						changePoint:480,visibleItems: 1},landscape: { changePoint:640,visibleItems: 2
						},tablet: {changePoint:768,visibleItems: 3}}});});
			</script>
		</div>				
	</div>
