<?php 
$id_evento       = $params[0];
$id_subevento    = $params[1];
$array_evento    = Evento::getEvento($id_subevento , 'all');
$array_subevento = Subevento::getSubevento($id_evento, $id_subevento, 'all');
?>
<?php foreach ($array_subevento as $subevento): ?>	
	<?php $valores = Subevento::getAllValues($subevento['id_subevento']);
		  $palestrante = Palestrante::getPalestrante($subevento['id_palestrante']); ?>
	<div class="tm-head">
		<h3><?= $subevento['titulo']?></h3>
	<div class="container fluid">
		<?php if(Media::image_exists($id_evento,$id_subevento)):?>
				<p>Imagens</p>
			<?php $img = Media::getAllImages($id_evento,$id_subevento);?> 
				<?=$img?>
		<?php endif; ?>
	</div>
	<style type="text/css">
		table>caption{font-size: 30px;font-weight: bold;text-shadow: 2px 2px 1px white;}
		table>thead>tr>th{text-align: center;font-size: 20px;font-weight: bold;}
	</style>
		<div class="row sub_describle" style="background:#D8D8D8">
			<div class="tm-head">
			<h3>Descrição</h3>
			<p><big>Tema:</big> <?= $subevento['descricao'] ?><br>
			<big>Palestrante:</big> <?= $palestrante['nome'] ?></p>
			<br><br>
			<div class="container fluid">
			<table class="table table-hover noBackground" style="margin-bottom:50px">
				<caption>Valores das Inscriçoes a cada dia</caption>
				<thead>
					<tr>
						<th>Data inicial</th>
						<th>Data final</th>
						<th>Valor</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($valores as $valor): ?>
					<tr>
						<td><?= $valor['data_ini'] ?></td>
						<td><?= $valor['data_fim'] ?></td>
						<td>R$ <?php echo number_format($valor['valor'],2) ?></td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			</div>
		</div>
		<?php if(Media::video_exists($id_evento,$id_subevento)):?>
			<div class="row sub_video" style="background:white;">
			<div class="container fluid">
				<div class="tm-head">
					<h3>Videos</h3>
					<p>Veja como será esse evento</p>
				</div>
				<?php $videos = Media::getAllVideos($id_evento,$id_subevento);?> 
					<?=$videos?>
			</div>
			</div>
		<?php endif; ?>
	</div>
<?php endforeach; ?>