
<div class="page-content">
  <div class="content container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-title">Home <small>Informações e Destaques</small></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget">
          <div class="widget-header"> <i class="icon-bookmark"></i>
            <h3>Atalhos Importantes</h3>
          </div>
          <div class="widget-content">
            <div class="shortcuts"> 
              <a class="shortcut" href="<?= App::getUrl() ?>admin/blocos"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Blocos Staticos</span> </a>
              <a class="shortcut" href="<?= App::getUrl() ?>admin/eventos"><i class="shortcut-icon icon-bookmark"></i><span class="shortcut-label">Eventos</span> </a>
              <a class="shortcut" href="<?=App::getUrl()?>admin/message/list"> <i class="shortcut-icon icon-comment"></i><span class="shortcut-label">Mensagens</span> </a>
              <a class="shortcut" href="<?=App::getUrl() ?>admin/new"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Usuarios</span> </a>
              <a class="shortcut" href="<?=App::getUrl()?>admin/eventos/list"><i class="shortcut-icon icon-facetime-video"></i><span class="shortcut-label">Videos</span> </a>
              <a class="shortcut" href="<?=App::getUrl()?>admin/eventos/list"><i class="shortcut-icon icon-picture"></i> <span class="shortcut-label">Fotos</span> </a>
              </div>
            </div>
          </div>
        </div>
      </div>
<div class="row">
        <div class="col-lg-12">
          <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
              <h3>Informações Sobre Inscrições</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">

              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th align="center"> <h3>Evento</h3> </th>
                    <th align="center"> <h3>Vagas</h3> </th>
                    <th align="center"> <h3>Inscritos</h3> </th>
                    <!-- <th align="center"> <h3>Remover da Lista</h3> </th> -->
                  </tr>
                </thead>
                <?php $eventos = Evento::getEvento(null, 'all');?>
                <tbody>
                <?php foreach($eventos as $evento ):?>
                  <tr>
                    <td> <?= $evento['titulo'] ?> </td>
                    <td align="center"> <?= $evento['vagas'] ?> </td>
                    <td align="center"> <?= EventoModel::countRegistered($evento['id_evento']) ?> </td>
                    <!-- <td class="td-actions"><a class="btn btn-danger btn-large" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td> -->
                  </tr>
                <?php endforeach; ?>  
                </tbody>
              </table>
              
            </div>
            <!-- /widget-content --> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>
