
    <div class="col-md-12 conteudo">
        <h1 class="titulo">Eventos</h1>
		<div class="row">
  			<div class="col-md-10">&nbsp;</div>
	  			<div class="container">
			    	<div class="row">
              <div class="col-xs-12 accordion">
                <div class="iten-calendario accord-header"><p>Semana Academica - Engenharia Civil&nbsp;<span class="glyphicon glyphicon-plus apresentar"></span></p></div>
                <div class="conteudo-calendario accord-content">
                    <table class="table table-hover">
                      <caption>Evento 1</caption>
                      <thead>
                        <tr>
                          <th>Data</th>
                          <th>Descricao</th>
                          <th>Vagas Totais</th>
                          <th>Inscrições Efetuadas</th>
                          <th>Inscrições Pagas</th>
                          <th>Vagas Restantes</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>01/03/14</td>
                          <td>Abertura</td>
                          <td>40</td>
                          <td>35</td>
                          <td>23</td>
                          <td>17</td>
                        </tr>
                        <tr>
                          <td>02/03/14</td>
                          <td>Palestra 1</td>
                          <td>20</td>
                          <td>15</td>
                          <td>13</td>
                          <td>7</td>
                        </tr>
                        <tr>
                          <td>03/03/14</td>
                          <td>minicurso 1</td>
                          <td>15</td>
                          <td>5</td>
                          <td>3</td>
                          <td>12</td>
                        </tr>
                        <tr>
                         <td>04/03/14</td>
                          <td>minicurso 2</td>
                          <td>15</td>
                          <td>5</td>
                          <td>3</td>
                          <td>12</td>
                        </tr>
                        <tr>
                          <td>05/03/14</td>
                          <td>Enceramento</td>
                          <td>40</td>
                          <td>35</td>
                          <td>23</td>
                          <td>17</td>
                        </tr>
                      </tbody>
                    </table>
                </div>
  
                <div class="iten-calendario accord-header"><p>Palestra Sobre Informatia e a Atualidade&nbsp;<span class="glyphicon glyphicon-plus apresentar"></span></p></div>
                <div class="conteudo-calendario accord-content">
                  <table class="table table-hover">
                      <caption>Informatica e a atualidade</caption>
                      <thead>
                         <tr>
                          <th>Data</th>
                          <th>Descricao</th>
                          <th>Vagas Totais</th>
                          <th>Inscrições Efetuadas</th>
                          <th>Inscrições Pagas</th>
                          <th>Vagas Restantes</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>10/04/14</td>
                          <td>Palestra</td>
                          <td>40</td>
                          <td>35</td>
                          <td>23</td>
                          <td>17</td>
                        </tr>
                      </tbody>
                    </table>
                </div>

                <div class="iten-calendario accord-header"><p>Amostra de Talentos - 2014&nbsp;<span class="glyphicon glyphicon-plus apresentar"></span></p></div>
                <div class="conteudo-calendario accord-content">
                  <table class="table table-hover">
                      <caption>Amostra de Talentos - 2014</caption>
                      <thead>
                        <tr>
                          <th>Data</th>
                          <th>Descricao</th>
                          <th>Vagas Totais</th>
                          <th>Inscrições Efetuadas</th>
                          <th>Inscrições Pagas</th>
                          <th>Vagas Restantes</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>20/06/14</td>
                          <td>1ª Noite</td>
                          <td>60</td>
                          <td>55</td>
                          <td>33</td>
                          <td>27</td>
                        </tr>
                        <tr>
                          <td>21/06/14</td>
                          <td>2ª Noite</td>
                          <td>45</td>
                          <td>35</td>
                          <td>15</td>
                          <td>30</td>
                        </tr>
                      </tbody>
                    </table>
                </div>
              </div>
					</div>
				</div>
		</div>	
	</div> 