
<div class="page-content">
  <div class="content container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-title">Home <small>Informações e Destaques</small></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget">
          <div class="widget-header"> <i class="icon-bookmark"></i>
            <h3>Atalhos Importantes</h3>
          </div>
          <div class="widget-content">
            <div class="shortcuts"> 
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Blocos Staticos</span> </a>
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-bookmark"></i><span class="shortcut-label">Eventos</span> </a>
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-signal"></i> <span class="shortcut-label">Informações</span> </a>
              <a class="shortcut" href="javascript:;"> <i class="shortcut-icon icon-comment"></i><span class="shortcut-label">Mensagens</span> </a>
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Usuarios</span> </a>
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-facetime-video"></i><span class="shortcut-label">Videos</span> </a>
              <a class="shortcut" href="javascript:;"><i class="shortcut-icon icon-picture"></i> <span class="shortcut-label">Fotos</span> </a>
              <a class="shortcut" href="javascript:;"> <i class="shortcut-icon icon-calendar"></i><span class="shortcut-label">Calendario</span> </a> </div>
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
      var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
        //alert(xhr.responseText);
    }
}
xhr.open('GET', 'http://www.previsaodotempo.org/api.php?city=Rio+de+Janeiro', true);
xhr.send(null);

$.get('http://www.previsaodotempo.org/api.php?city=Rio+de+Janeiro', function(responseText) {
    alert(responseText);
});
       

</script>
<div class="row">
        <div class="col-lg-12">
          <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
              <h3>Informações Sobre Inscrições</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">

              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th> Evento </th>
                    <th> Vagas </th>
                    <th> Inscritos </th>
                    <th class="td-actions"> </th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  <tr>
                    <td> abc </td>
                    <td> 123 </td>
                    <td> 100 </td>
                    <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                  </tr>
                  
                </tbody>
              </table>
              
            </div>
            <!-- /widget-content --> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>
