<div class="page-content">
  <div class="content container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-title">Inserir Sub-eventos <small>Selecione o Evento Principal</small></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget widget-table action-table">
          <div class="widget-header"> <i class="icon-th-list"></i>
            <h3>Eventos Cadastrados</h3>
          </div>
          <!-- /widget-header -->
          <div class="widget-content">
          <?php if(Evento::exists()): ?>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Tiulo </th>
                  <th> Descrição </th>
                  <th> Data&nbsp;do&nbsp;Evento </th>
                  <th> Número de inscritos </th>
                  <th> Inserir&nbsp;Subevento </th>
                  <th> Inserir media</th>
                  <th> Excluir</th>
                </tr>
              </thead>
              <tbody>
              <?php $eventos = Evento::getEvento(null, 'all');?>
              <?php foreach ($eventos as $evento):?>
                <tr>
                  <td><?= $evento['titulo']?></td>
                  <td><?= $evento['descricao_resumida']?></td>
                  <td><?= $evento['data_hora']?></td>
                  <td><?= EventoModel::countRegistered($evento['id_evento']) ?></td>
                  <td class="td-actions"><a class="btn btn-success" href="<?= App::getUrl() ?>admin/subeventos/<?= $evento['id_evento'] ?>/new"><i class="btn-icon-only icon-plus"> </i></a></td>
                  <td class="td-actions"><a class="btn btn-primary" href="<?= App::getUrl() ?>admin/eventos/media/<?= $evento['id_evento'] ?>"><i class="btn-icon-only icon-pencil"> </i></a></td>
                  <td class="td-actions"><a class="btn btn-danger" href="<?= App::getUrl() ?>admin/eventos/delete/<?= $evento['id_evento'] ?>"><i class="btn-icon-only icon-trash"> </i></a></td>
                </tr>
              <?php endforeach; ?>
              </tbody>
            </table>
          <?php else:?>
            <h3 style="text-align:center"><p>Não há Eventos Cadastrados...</p></h3>
          <?php endif;?>
          </div>
          <!-- /widget-content --> 
        </div>
      </div>
    </div>
  </div>
</div>