<script type="text/javascript">
  $(document).ready(function() {
    $(".accordion .accord-header").click(function() {
      if($(this).next("div").is(":visible")){
        $(this).next("div").slideUp("slow");
      } else {
        $(".accordion .accord-content").slideUp("slow");
        $(this).next("div").slideToggle("slow");
      }
    });
  });
</script>
<?php
  Page::addThinElement('js', 'jquery.js');
  Page::addStyleElement('js', 'bootstrap.min.js');
  Page::addStyleElement('js', 'custom.js');
  Page::addThinElement('js', 'smooth-sliding-menu.js');


  Page::addCkeditorElement('css', 'skins/moono/editor.css');
    Page::addCkeditorElement('js', 'config.js');
    Page::addCkeditorElement('js', 'ckeditor.js');
    Page::addCkeditorElement('js', 'lang/pt-br.js');
    Page::addCkeditorElement('js', 'styles.js');
 
?>

</body>
</html>