<div class="footer"><p>© Copyright 2014&nbsp;&nbsp;<a href="#"><?php Page::addImage('Ponto.png', 'style="width:10%"');?></a></p></div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".accordion .accord-header").click(function() {
      if($(this).next("div").is(":visible")){
        $(this).next("div").slideUp("slow");
      } else {
        $(".accordion .accord-content").slideUp("slow");
        $(this).next("div").slideToggle("slow");
      }
    });
  });
</script>
</body>
</html>