<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<title>Area do Administrador</title>
    <?php
      Page::addStyleElement('css', 'bootstrap.min.css');
      Page::addStyleElement('css', 'bootstrap-theme.min.css');
      Page::addStyleElement('css', 'custom.css');
      Page::addStyleElement('js', 'bootstrap.min.js');
      Page::addStyleElement('js', 'jquery.min.js');
      Page::addStyleElement('js', 'bootstrap.min.js');
      Page::addStyleElement('js', 'custom.js');
    ?>
</head>