<!DOCTYPE html>
<html>
<head>
<?php
    header( "Access-Control-Allow-Origin: http://localhost/integrador/" ); 
    AdminModel::islogged();
?>
   <meta charset='utf-8'>
   <title>Area do Administrador</title>
   <?php
   Page::addThinElement('css', 'bootstrap.css');
   Page::addThinElement('css', 'thin-admin.css');
   Page::addThinElement('css', 'font-awesome.css');
   Page::addThinElement('css', 'style.css');
   Page::addThinElement('css', 'dashboard.css');
   Page::addThinElement('css', 'tema.css');
   Page::addStyleElement('css', 'custom.css');
   Page::addStyleElement('js', 'jquery.min.js');
   ?>
   <!-- para internet explorer -->
<!--[if lt IE 9]>
      <?php
         Page::addThinElement('js', 'html5shiv.js');
         Page::addThinElement('js', 'respond.min.js');
      ?>
    <![endif]-->
</head>
<body>
   <div class="container">
      <div class="top-navbar header b-b"> 
         <a data-original-title="Toggle navigation" class="toggle-side-nav pull-left" href="#"><i class="icon-reorder"></i> </a>
         <a class="navbar-brand name_admin" href="#">Olá&nbsp;<?= $_SESSION['name'] ?></a>

         <ul class="nav navbar-nav navbar-right  hidden-xs">
            
            <li class="dropdown user  hidden-xs"> <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="icon-male"></i> <span class="username"><?= $_SESSION['name'] ?></span> <i class="icon-caret-down small"></i> </a>
             <ul class="dropdown-menu">
               <li><a href="#"><i class="icon-user"></i> Minha Conta</a></li>
               <li><a href="#"><i class="icon-calendar"></i> Calendario</a></li>
               <li><a href="#"><i class="icon-cogs"></i> Configurações</a></li>
               <li class="divider"></li>
               <li><a href="<?= App::getUrl() ?>admin/logout"><i class="icon-signout"></i> Sair</a></li>
            </ul>
         </li>
      </ul>
   </div>
</div> 

<div class="wrapper">
  <div class="left-nav">
    <div id="side-nav">
      <ul id="nav">
        <li> <a href="<?= App::getUrl() ?>admin/index"> <i class="icon-desktop"></i> Home</a></li>
        <li> <a href="#"> <i class="icon-glass"></i> EVENTOS <span class="label label-info pull-right">2</span><i class="arrow icon-angle-up"></i></a>
        	<ul class="sub-menu">
        		<li><a href="<?= App::getUrl() ?>admin/eventos/new"><i class="icon-angle-right"></i> Inserir </a></li>
        		<li><a href="#"><i class="icon-angle-right"></i> Editar / Excluir </a></li>
        	</ul>
        </li>
        <li> <a href="#"> <i class="icon-group"></i> PALESTRANTES <span class="label label-info pull-right">2</span><i class="arrow icon-angle-up"></i></a>
        <ul class="sub-menu">
        	<li><a href="<?= App::getUrl() ?>admin/palestrantes/new"><i class="icon-angle-right"></i> Inserir </a></li>
        	<li><a href="#" ><i class="icon-angle-right"></i> Editar / Excluir</a></li>
        </ul>
        </li>
        <li> <a href="#"> <i class="icon-list-alt"></i> Blocos estaticos <span class="label label-info pull-right">2</span><i class="arrow icon-angle-up"></i></a>
          <ul class="sub-menu">
            <li><a href="<?= App::getUrl() ?>admin/blocos/new"><i class="icon-angle-right"></i> Inserir </a></li>
            <li><a href="<?= App::getUrl() ?>admin/blocos/edit" ><i class="icon-angle-right"></i> Editar / Excluir</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>