<!DOCTYPE html>
<html>
<head>
  <?php
  header( "Access-Control-Allow-Origin: http://localhost/integrador/" ); 
  if(!AdminModel::islogged()){
   App::redirect(App::getUrl().'login/verify/admin');
   exit();
 }
 App::ready();
 ?>
 <meta charset='utf-8'>
 <title>Area do Administrador</title>
 <?php
 Page::addThinElement('css', 'bootstrap.css');
 Page::addThinElement('css', 'thin-admin.css');
 Page::addThinElement('css', 'font-awesome.css');
 Page::addThinElement('css', 'style.css');
 Page::addThinElement('css', 'dashboard.css');
 Page::addThinElement('css', 'tema.css');
 Page::addStyleElement('css', 'custom.css');
 Page::addStyleElement('js', 'jquery.min.js');
 Page::addStyleElement('js', 'custom.js');
 ?>
<script>
  setTimeout(function(){
     $('.alert').remove();
},1900);
</script>
 <!-- para internet explorer -->
<!--[if lt IE 9]>
      <?php
         Page::addThinElement('js', 'html5shiv.js');
         Page::addThinElement('js', 'respond.min.js');
      ?>
      <![endif]-->
    </head>
    <body>
     <div class="container">
      <div class="top-navbar header b-b"> 
       <a data-original-title="Toggle navigation" class="toggle-side-nav pull-left" href="#"><i class="icon-reorder"></i> </a>
       <a class="navbar-brand name_admin" href="#">Olá&nbsp;<?= $_SESSION['adm']['name'] ?></a>

       <ul class="nav navbar-nav navbar-right  hidden-xs">

        <!--Mensagens-->
        <?php $data = Admin::getMsg();?>
        <?php if($data !== null):?>
        <li class="dropdown"> 
          <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="icon-envelope"></i> 
            <span class="badge"><?=AdminModel::verifyMsg($_SESSION['adm']['email'])?></span> 
          </a>
          <ul class="dropdown-menu extended notification">
            <li class="title" style="margin-top:0px!important">
              <p>Voce Tem <?=AdminModel::verifyMsg($_SESSION['adm']['email'])?> nova(s) menssagen(s)</p>
            </li>
            <?php foreach ($data as $d):?>
            <li> 
              <a href="#">
                <span class="subject"> <span class="from"><?=$d[1]?></span> </span> 
                <span class="text"><?=$d[2]?></span> 
              </a> 
            </li>
          <?php endforeach;?>
            <li class="footer_msg"> <a href="<?=App::getUrl()?>admin/message/list">Ver todas as Menssagens</a> </li>
          </ul>
        </li>
      <?php endif;?>
        <!--Mensagens-->
        <li class="dropdown user  hidden-xs"> <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="icon-male"></i> <span class="username"><?= $_SESSION['adm']['name'] ?></span> <i class="icon-caret-down small"></i> </a>
         <ul class="dropdown-menu">
           <!-- <li><a href="#"><i class="icon-user"></i> Minha Conta</a></li>
           <li><a href="#"><i class="icon-calendar"></i> Calendario</a></li>
           <li><a href="#"><i class="icon-cogs"></i> Configurações</a></li>
           <li class="divider"></li> -->
           <li><a href="<?= App::getUrl() ?>admin/logout"><i class="icon-signout"></i> Sair</a></li>
         </ul>
       </li>
     </ul>
   </div>
 </div> 

 <div class="wrapper">
  <div class="left-nav">
    <div id="side-nav">
      <ul id="nav">
        <li> <a href="<?= App::getUrl() ?>admin/index"> <i class="icon-desktop"></i> Home</a></li>

        <li> <a href="#"> <i class="icon-glass"></i> EVENTOS<i class="arrow icon-angle-up"></i></a>
        	<ul class="sub-menu">
        		<li><a href="<?= App::getUrl() ?>admin/eventos/new"><i class="icon-angle-right"></i> Inserir </a></li>
        		<li><a href="<?= App::getUrl() ?>admin/eventos/list"><i class="icon-angle-right"></i> Editar/Excluir </a></li>
        	</ul>
        </li>
        <li> <a href="#"> <i class="icon-pushpin"></i> SUBEVENTOS<i class="arrow icon-angle-up"></i></a>

          <ul class="sub-menu">
            <li><a href="<?= App::getUrl() ?>admin/eventos/list"><i class="icon-angle-right"></i> Inserir </a></li>
            <li><a href="<?= App::getUrl() ?>admin/subeventos/list"><i class="icon-angle-right"></i> Editar/Excluir </a></li>
          </ul>
        </li>
        <li> <a href="#"> <i class="icon-group"></i> PALESTRANTES<i class="arrow icon-angle-up"></i></a>
          <ul class="sub-menu">
           <li><a href="<?= App::getUrl() ?>admin/palestrantes/new"><i class="icon-angle-right"></i> Inserir </a></li>
           <li><a href="<?= App::getUrl() ?>admin/palestrantes" ><i class="icon-angle-right"></i> Excluir</a></li>
         </ul>
       </li>
       <li> <a href="#"> <i class="icon-list-alt"></i> Blocos estaticos<i class="arrow icon-angle-up"></i></a>
        <ul class="sub-menu">
          <li><a href="<?= App::getUrl() ?>admin/blocos/new"><i class="icon-angle-right"></i> Inserir </a></li>
          <li><a href="<?= App::getUrl() ?>admin/blocos" ><i class="icon-angle-right"></i> Editar</a></li>
        </ul>
      </li>
      <li> <a href="#"> <i class="icon-list-alt"></i> Email<i class="arrow icon-angle-up"></i></a>
        <ul class="sub-menu">
          <li><a href="<?= App::getUrl() ?>admin/message/list"><i class="icon-angle-right"></i> listar Email </a></li>
          <li><a href="<?= App::getUrl() ?>admin/recontact" ><i class="icon-angle-right"></i> Enviar Email</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>