<div class="page-content">
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title">Criar Blocos Estaticos <small>Crie Aqui novos blocos</small></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget">
					<div class="widget-header"> <i class="icon-align-left"></i>
						<h3>Blocos</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="widget widget-table action-table">
							<textarea class="ckeditor" name="editor1"></textarea>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	

