<!-- Fim do menu -->
<div class="page-content">
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title">Inserir Sub-eventos <small>Cadastre aqui os novos sub-eventos</small></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget">
					<div class="widget-header"> <i class="icon-align-left"></i>
						<h3>Sub-eventos</h3>
					</div>
					<div class="widget-content">
						<form method="post" class="form-horizontal" action="<?= App::getUrl() ?>admin/subeventos/<?= $id_evento ?>/new/post">
							<fieldset>
								<legend class="section">Informações Sobre o Sub-evento</legend>
								<div class="control-group">
									<label for="disabled-input" class="control-label ">Titulo Do Sub-evento</label>
									<div class="controls form-group">
										<input type="text" maxlength="50" name="titulo" class="form-control" id="titulo">
									</div>
								</div>
								<div class="control-group">
									<label for="disabled-input" class="control-label ">Data Do sub-evento</label>
									<div class="controls form-group">
										<input type="datetime-local" name="data_hora" class="form-control" id="data-hora">
									</div>
								</div>
								<div class="control-group">
									<label for="disabled-input" class="control-label ">Local do sub-evento</label>
									<div class="controls form-group">
										<input type="text" name="local" class="form-control" id="local">
									</div>
								</div>
								<div class="control-group">
									<label for="disabled-input" class="control-label ">Descrição do sub-evento</label>
									<div class="controls form-group">
										<textarea class="desc-evento" name="desc_subevento"></textarea>
									</div>
								</div>
								<div class="control-group">
									<label for="max-length" class="control-label ">Fim Inscrições</label>
									<div class="controls form-group">
										<input type="date" class="form-control" name="data_limite" id="data-limite" placeholder="Data Limite Para As Inscriçoes">
									</div>
								</div>
								<div class="control-group">
									<label for="prepended-input" class="control-label">Vagas</label>
									<div class="controls form-group">
										<input type="number" class="form-control" name="vagas" id="vagas" placeholder="Quantidade de vagas">
									</div>
								</div>
								<div class="date">
									<div class="controls form-group">
										<a id="add-inscricao" class="btn btn-warning" onclick="inserir_inscricao();">Adicionar período de inscrições</a>
									</div>
									<div id="valores-inscricoes"></div>
								</div>
							</fieldset>
							<fieldset>
								<legend class="section">Ministrante</legend>
								<div class="control-group">
									<label for="normal-field" class="control-label">Palestrante</label>
									<div class="controls form-group">
										<select name="palestrante" class="form-control">
											<option> -- Selecione o Palestrante --</option>
											<?php foreach ($palestrantes as $palestrante) {
												echo '<option value="'.$palestrante['id_palestrante'].'">'.$palestrante['nome'].'</<option value=""></option>>';
											} ?>
										</select>
									</div>
								</div>
							</fieldset>
							<div class="form-actions">
								<div class="btn-actions">
									<button class="btn-action btn btn-success" type="submit">Inserir sub-evento</button>
									<button class="btn-action btn btn-default" type="button">Cancelar</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	var i = 0;
	$(function(){
		$('.estados').change(function(){
			var url_ = "<?= App::getUrl() ?>";
			url_ += 'local/ajax/'+$(this).val();
			var request = $.ajax({
				url : url_,
				type : 'get',
				success : function(e){
					$('#cidade').show(300);
					var html = e ;
					$('.cidade').html(html);
				}
			});
		});
	});
	function inserir_inscricao(){
		i++;
		var data_insc = "<div class='data"+i+"'><div class='controls form-group'>Data inicio <input type='date' name='valores["+i+"][data_ini]'> Data final <input type='date' name='valores["+i+"][data_fim]'> Valor <input type='text' name='valores["+i+"][valor]'> <a class='plus btn btn-primary' onclick='inserir_inscricao();'>+</a>&nbsp;<a class='del"+i+" btn btn-danger' onclick='deletar_inscricao("+i+");'>-</a></div></div>";

		$('#valores-inscricoes').append(data_insc).hide().fadeIn(200);
	}
	function deletar_inscricao(id){
		$('.data'+id+'').hide(100);
	}
</script>