    <!-- Fim do menu -->
    <!-- calendario -->
    <div class="col-md-12 conteudo">
      <h1 class="titulo">Criar Evento</h1>
  		<div class="row">
    		<div class="col-md-10">&nbsp;</div>
  	  		<div class="container">
  			   	<div class="row">
              <div class="col-xs-12">
                <form role="form">
                  <div class="form-group">
                    <label>Local Do Evento</label>
                    <input type="text" class="form-control" id="local" placeholder="Localidade do Evento">
                  </div>
                  <div class="form-group">
                    <label>Palestrante</label>
                    <select name="palestrante">
                      <?php foreach ($palestrantes as $palestrante) {
                          echo '<option value="'.$palestrante['id_palestrante'].'">'.$palestrante['nome'].'</option>';
                      } ?>
                    </select>
                  </div>
                  <div class="form-inline">
                    <label for="exampleInputFile">Data Do Evento</label>
                    <input type="datetime-local" class="form-control" id="data-hora">
                    <label for="exampleInputFile">Data Limite das Inscrições</label>
                    <input type="date" class="form-control" id="data-limite">
                    <label for="exampleInputFile">Vagas</label>
                    <input type="number" class="form-control" id="vagas" placeholder="Quantidade de vagas">
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" id="habilitar-inscricoes"> Habilitar Inscrições para o Evento?
                    </label>
                  </div>
                  <div class="form-group">
                    <label>Descrição Sobre o Evento</label><br>
                    <textarea class="desc-evento" name="Descricao-evento" rows="10" cols="20"></textarea>
                  </div>
                  <div class="form-group">
                    <label>Email Contato</label>
                    <input type="email" class="form-control" id="contato-email" placeholder="Email para Contato">
                  </div>
                  <div class="form-inline">
                    <label>Telefone Contato</label>
                    <input type="text" class="form-control" id="contato-telefone" placeholder="Telefone para Contato">
                    <label>Estado</label>
                    <select name="estado" class="form-control">
                      <option value="">Pr</option>
                      <option value="">Sc</option>
                      <option value="">Rs</option>
                    </select>
                    <label>Cidade</label>
                    <select name="cidade" class="form-control">
                      <option value="">Guarapuava</option>
                      <option value="">Ponta Grossa</option>
                      <option value="">Maringa</option>
                    </select>
                  </div>
                  <div class="form-group"></div>
                  <div class="form-inline">
                     <label>Administrador do Evento</label>
                     <select name="administrador" class="form-control">
                       <option value="">Admin 1</option>
                       <option value="">Admin 2</option>
                       <option value="">Admin 3</option>
                    </select>
                  </div>
                  <div class="form-group submit">
                    <button type="submit" class="btn btn-default">Submit</button>
                  </div>
                </form>
              </div>
            </div>
  				</div>
  		</div>
		</div> 
