<?php
Page::addTinymceElement('js', 'js/tinymce/tinymce.min.js'); 
?>

<div class="page-content">
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title">Criar Blocos Estaticos <small>Crie Aqui novos blocos</small></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget-header"> <i class="icon-align-left"></i>
					<h3>Blocos</h3>
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="widget-content">

							<form method="POST" action="<?= App::getUrl() ?>admin/blocos/new/post">
								<div class="control-group">
									<label for="normal-field" class="control-label">Id do bloco</label>
									<div class="controls form-group">
										<input type="text" name="id_bloco" placeholder="Nome pelo qual será referenciado" class="form-control" id="normal-field" maxlength="30">
									</div>
								</div>
								<textarea id="elm1" name="html"></textarea><br>
								<div class="btn-actions">
									<input type="submit" value="Salvar" class="btn-action btn btn-success"><br><br>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	tinymce.init({
		selector: "textarea#elm1",
		theme: "modern",
		language : 'pt_BR',
		height: 320,
		plugins: [
		"advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
		"searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
		"save table contextmenu directionality emoticons template paste textcolor"
		],
		content_css: "css/content.css",
		toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
		style_formats: [
		{title: 'Bold text', inline: 'b'},
		{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
		{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
		{title: 'Example 1', inline: 'span', classes: 'example1'},
		{title: 'Example 2', inline: 'span', classes: 'example2'},
		{title: 'Table styles'},
		{title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
		]
	});
	tinymce.init({
		selector: "textarea"
	}); 
</script>

