
<div class="page-content">
	<div class="content container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title">Inserir Palestrante <small>Cadastre aqui os novos palestrantes</small></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="widget">
					<div class="widget-header"> <i class="icon-user"></i>
						<h3>Palestrante</h3>
					</div>
					<div class="widget-content">
						<form action="<?= App::getUrl() ?>admin/palestrantes/new/post" method="POST" enctype="multipart/form-data" class="form-horizontal">
							<fieldset>
								<legend class="section">Informações Pessoais</legend>
								<div class="control-group">
									<label for="normal-field" class="control-label">Nome</label>
									<div class="controls form-group">
										<input required="required" type="text" name="nome" placeholder="Digite o nome do palestrante" class="form-control" id="normal-field">
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Data de nascimento </label>
									<div class="controls form-group">
										<input required="required" type="date" name="data_nascimento" class="form-control">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Formação </label>
									<div class="controls form-group">
										<select name="id_formacao" class="form-control">
											<?php foreach ($formacoes as $formacao) {
												echo '<option value="'.$formacao['id_formacao'].'">'.$formacao['nome'].'</option>';
											} ?>	
										</select>  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Descrição </label>
									<div class="controls form-group">
										<textarea class="desc-evento" name="descricao" placeholder="Digite aqui as informações sobre o Palestrante"></textarea>
									</div>
								</div>
							</fieldset>
							<fieldset>
								<legend class="section">Endereço</legend>
								<div class="control-group">
									<label for="disabled-input" class="control-label ">Estado</label>
									<div class="controls form-group">
										<div class="estado"><?= Local::getSelectEstados() ?></div>
									</div>
								</div>
								<div class="control-group" id="cidade" style="display:none">
									<label for="hint-field" class="control-label"> Cidade </label>
									<div class="controls form-group">
										<div class="cidade"></div>
									</div>
								</div>
							</fieldset>
							<fieldset>
								<legend class="section">Contato</legend>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Email </label>
									<div class="controls input-group form-group">
										<span class="input-group-addon"><i class="icon-envelope"></i></span>
										<input required="required" type="email" name="email" class="form-control" placeholder="Digite o email do palestrante">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Telefone </label>
									<div class="controls input-group form-group">
										<span class="input-group-addon"><i class="icon-phone-sign"></i></span>
										<input required="required" type="text" name="telefone" class="form-control" placeholder="Digite o telefone do palestrante">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Facebook </label>
									<div class="controls input-group form-group">
										<span class="input-group-addon"><i class="icon-facebook-sign"></i></span>
										<input required="required" type="text" name="facebook" class="form-control" placeholder="Digite endereço eletronico do facebook do palestrante">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Twitter </label>
									<div class="controls input-group form-group">
										<span class="input-group-addon"><i class="icon-twitter"></i></span>
										<input required="required" type="text" name="twitter" class="form-control" placeholder="Digite endereço eletronico do Twitter do palestrante">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Google + </label>
									<div class="controls input-group form-group">
										<span class="input-group-addon"><i class="icon-google-plus"></i></span>
										<input required="required" type="text" name="google_plus" class="form-control" placeholder="Digite endereço eletronico do google + do palestrante">  
									</div>
								</div>
								<div class="control-group">
									<label for="hint-field" class="control-label"> Foto: </label>
									<div class="controls input-group form-group">
										<span class="input-group-btn"><span class="btn btn-success btn-file">Procurar... <input required="required" type="file" name="image" id="file" onchange="pega_valor(this.value);"></span></span><input required="required" type="text" name="copyImage" class="form-control" id="replace" readonly=""></div> 
									</div>
								</div>
							</fieldset>
							<div class="form-actions">
								<div class="btn-actions">
									<button class="btn-action btn btn-success" type="submit">Inserir Palestrante</button>
									<button class="btn-action btn btn-default" type="button">Cancelar</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
	$(function(){
		$('.estados').change(function(){
			var url_ = "<?= App::getUrl() ?>";
			url_ += 'local/ajax/'+$(this).val();
			var request = $.ajax({
				url : url_,
				type : 'get',
				success : function(e){
					$('#cidade').show(300);
					var html = e ;
					$('.cidade').html(html);
				}
			});
		});
	});
	function pega_valor(caminho){
			$('#replace').val(caminho);
    	};
</script>