<div class="page-content">
  <div class="content container">
    <div class="row">
      <div class="col-lg-12">
        <div class="widget widget-table action-table">
          <div class="widget-header"> <i class="icon-th-list"></i>
            <h3>Menssagens</h3>
          </div>
          <!-- /widget-header -->
          <div class="widget-content">
          <?php $data = Admin::getMsg();?>
          <?php if($data !== null):?>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Usuario </th>
                  <th> Email </th>
                  <th> Menssagen </th>
                  <th> Evento </th>
                  <th class="td-actions">Responder/Excluir</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($data as $d): ?> 
                <tr>
                  <td> <?=$d[1]?> </td>
                  <td> <?=$d[2]?> </td>
                  <td> <?=$d[3]?> </td>
                  <td> <?php $evento = Evento::getEvento($d[5],'info');echo $evento[0]['titulo'];?> </td>
                  <td class="td-actions"><a class="btn btn-small btn-success" href="<?=App::getUrl()?>admin/sendmail/"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                </tr>
              <?php endforeach;?>
              </tbody>
            </table>
          <?php else: ?>
            <h3>Não há Mensagens Para Você</h3>
          <?php endif; ?>

          </div>
          <!-- /widget-content --> 
        </div>
      </div>
    </div>
  </div>
</div>