<div class="page-content">
  <div class="content container">
    <div class="row">
      <div class="col-lg-12">
        <div class="widget widget-table action-table">
          <div class="widget-header"> <i class="icon-th-list"></i>
            <h3>Informações Sobre Blocos</h3>
          </div>
          <!-- /widget-header -->
          <div class="widget-content">

            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Id Do Bloco </th>
                  <th> Trecho HTML </th>
                  <th> Referencia </th>
                  <th class="td-actions">Editar/Excluir</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td> abc </td>
                  <td> 123 </td>
                  <td> 100 </td>
                  <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                </tr>
                <tr>
                  <td> abc </td>
                  <td> 123 </td>
                  <td> 100 </td>
                  <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                </tr>
                <tr>
                  <td> abc </td>
                  <td> 123 </td>
                  <td> 100 </td>
                  <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                </tr>
                <tr>
                  <td> abc </td>
                  <td> 123 </td>
                  <td> 100 </td>
                  <td class="td-actions"><a class="btn btn-small btn-success" href="javascript:;"><i class="btn-icon-only icon-ok"> </i></a><a class="btn btn-danger btn-small" href="javascript:;"><i class="btn-icon-only icon-remove"> </i></a></td>
                </tr>

              </tbody>
            </table>

          </div>
          <!-- /widget-content --> 
        </div>
      </div>
    </div>
  </div>
</div>