<div class="page-content">
  <div class="content container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-title">Sub-eventos <small>Eventos e seus subeventos</small></h1>
      </div>
    </div>
     <?php if(Evento::exists()): ?>
        <?php $eventos = Evento::getEvento(null, 'all');?>
        <?php foreach ($eventos as $evento):?>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget widget-table action-table">
          <div class="widget-header"> <i class="icon-th-list"></i>
            <h3><?= $evento['titulo'] ?>&nbsp;-&nbsp;Subeventos</h3>
          </div>
          <!-- /widget-header -->
          <div class="widget-content">
            <?php if(Subevento::exists($evento['id_evento'])): ?>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Nome </th>
                  <th> Data&nbsp;do&nbsp;Subevento </th>
                  <th> Número de inscritos </th>
                  <th> Inserir media</th>
                  <th> Excluir</th>
                </tr>
              </thead>
              <tbody>
                <?php $subeventos = Subevento::getSubevento($evento['id_evento'],null, 'all');?>
                <?php foreach ($subeventos as $subevento):?>
                <tr>
                  <td><?= $subevento['titulo'] ?></td>
                  <td><?= $subevento['data_hora'] ?></td>
                  <td><?= SubeventoModel::countRegistered($subevento['id_subevento']) ?></td>
                  <td class="td-actions"><a class="btn btn-primary" href="<?= App::getUrl('admin/subeventos/media/'.$subevento['id_subevento']) ?>"><i class="btn-icon-only icon-pencil"> </i></a></td>
                  <td class="td-actions"><a class="btn btn-danger" href="<?= App::getUrl('admin/subeventos/delete/'.$subevento['id_subevento']) ?>"><i class="btn-icon-only icon-trash"> </i></a></td>
                </tr>
              <?php endforeach; ?>
              </tbody>
            </table>
          <?php else: ?>
              <h3 style="text-align:center"><p>Não há Subeventos Cadastrados...</p></h3>
          <?php endif; ?>
          </div>
          <!-- /widget-content --> 
        </div>
      </div>
    </div>
     <?php endforeach; ?>
      <?php else:?>
            <h3 style="text-align:center"><p>Não há Eventos Cadastrados...</p></h3>
          <?php endif;?>
  </div>
</div>