<?php
  include_once '../core/App.class.php';
  $app = new App();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<title>Area do Administrador</title>
	 <?php
      Page::addStyleElement('css', 'bootstrap.min.css');
      Page::addStyleElement('css', 'bootstrap-theme.min.css');
      Page::addStyleElement('css', 'custom.css');
      Page::addStyleElement('js', 'bootstrap.min.js');
      Page::addStyleElement('js', 'jquery.min.js');
      Page::addStyleElement('js', 'bootstrap.min.js');
    ?>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<!--       <div class="container"> -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bem Vindo //*Admin*//</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="area_admin.phtml">Home</a></li>
            <li><a href="inserir_eventos.phtml">Inserir Eventos</a></li>
            <li class="active"><a href="editar_eventos.phtml">Editar Eventos</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle drop-user" data-toggle="dropdown">//*Admin*//&nbsp;<span class="glyphicon glyphicon-user"></span><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"><span class="glyphicon glyphicon-plus"></span>&nbsp;Criar nova conta Administrador</a></li>
                <li class="divider"></li>
                <li><a href="#"><span class="glyphicon glyphicon-user"></span>&nbsp;Minha Conta</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-cog"></span>&nbsp;Configurações</a></li>
                <li class="divider"></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Sair</a></li>
              </ul>
            </li>
          </ul>
        </div>
      <!-- </div> -->
    </div>
    <!-- Fim do menu -->
    <!-- calendario -->
    <div class="col-md-12 conteudo">
      <h1 class="titulo">Editar Eventos</h1>
      <div class="row">
        <div class="col-md-10">&nbsp;</div>
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>Id  - Evento</th>
                          <th>Nome</th>
                          <th>Descricao</th>
                          <th>Acessar</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <td>1</td>
                          <td>Semana Academica Engenharia Civíl</td>
                          <td> - </td>
                          <td><a href="#">Editar&nbsp;<span class="glyphicon glyphicon-pencil"></span></a></td>
                      </tr>
                      <tr>
                          <td>2</td>
                          <td>Palestra</td>
                          <td>Informatica na atualidade</td>
                          <td><a href="#">Editar&nbsp;<span class="glyphicon glyphicon-pencil"></span></a></td>
                      </tr>
                      <tr>
                          <td>3</td>
                          <td>Amostra de Talentos</td>
                          <td>3ª Amostra de Talentos UTFPR - Guarapuava</td>
                          <td><a href="#">Editar&nbsp;<span class="glyphicon glyphicon-pencil"></span></a></td>
                      </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
      </div>
    </div> 
    <div class="footer">
       <p>© Copyright 2014 Criado por&nbsp;<a href="#">PontoEdu.br</a></p>
    </div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".accordion .accord-header").click(function() {
      if($(this).next("div").is(":visible")){
        $(this).next("div").slideUp("slow");
      } else {
        $(".accordion .accord-content").slideUp("slow");
        $(this).next("div").slideToggle("slow");
      }
    });
  });
</script>
</body>
</html>