<?php App::ready(); ?>
<!DOCTYPE html>
<html>
<head>
	<title>Pagina Não Encontrada</title>

	<?php
	Page::addThinElement('css', 'bootstrap.css');
	Page::addThinElement('css', 'thin-admin.css');
	Page::addThinElement('css', 'font-awesome.css');
	Page::addThinElement('css', 'style.css');
	Page::addStyleElement('js', 'jquery.min.js');
	?>

</head>
<body>

<div class="widget-404" style="margin-top: 50px;">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-align-center">404 !</h1>
		</div>
		<div class="col-md-12">
			<div class="description">
				<h3>Oops! Parece que você está perdido.</h3>
				<p>A página que você procurou não existe ou não foi encontrada.<br><bt>
				<div class="back-home">
					<strong><a href="<?= App::getUrl() ?>"><i class="icon-home"></i> Volte Para Pagina Principal <i class="icon-home"></i></a></strong></p>
				</div>
			</div>
			<?= Blocos::writer('pontoedu'); ?>
		</div>
	</div>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="js/jquery.js"></script> 
<script src="js/bootstrap.min.js"></script> 

</body>
</html>
